Pandas & Data Cleaning Demo

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /Users/krishikasandiri/Downloads/Bomber Belts 2015/.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /Users/krishikasandiri/Downloads/Bomber Belts 2015/.venv/lib/python3.12/site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/krishikasandiri/Downloads/Bomber Belts 2015/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/krishikasandiri/Downloads/Bomber Belts 2015/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/krishikasandiri/Downloads/Bomber Belts 2015/.venv/lib/python3.12/site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /Users/krishikasandiri/Downloads/Bomber Belts 2015/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('datasets/background survey.csv')

In [6]:
df.head()

,Timestamp,What is your name?,Did you grow up in North Carolina?,How old are you?,What level of a student are you?,"How familiar are you with ""data science""?","How familiar are you with ""social science""",How nervous are you for this class?,Are you excited for this class?,"How do you think generative AI should be used or treated in this course? Don't be shy, we're looking for honest, insightful ideas,"
0,2026/01/11 7:00:22 PM EST,First Last 1,Yes,20,Sophomore,3,3,5,Yes,AI should be used to help with learning materi...
1,2026/01/11 7:52:56 PM EST,First 2,Yes,23,Junior,2,1,3,Maybe,I think generative AI can be used to help supp...
2,2026/01/11 8:29:18 PM EST,First Last 3,No,21,Junior,4,5,3,Yes,I don't think we should rely on it. I think it...
3,2026/01/12 12:45:08 AM EST,First Last 4,Yes,20,Junior,3,3,2,Yes,Encouraged
4,2026/01/12 8:43:02 AM EST,First Last 5,Yes,20,Junior,4,2,2,Maybe,I think generative AI should be used wisely in...

In [7]:
df.tail()

,Timestamp,What is your name?,Did you grow up in North Carolina?,How old are you?,What level of a student are you?,"How familiar are you with ""data science""?","How familiar are you with ""social science""",How nervous are you for this class?,Are you excited for this class?,"How do you think generative AI should be used or treated in this course? Don't be shy, we're looking for honest, insightful ideas,"
95,2026/01/13 9:23:32 PM EST,First Last 36,No,20,Junior,4,2,3,Yes,Only as a tool for help better learning
96,2026/01/13 11:24:47 PM EST,First Last 83,No,35,Junior,4,4,1,Yes,"I think we should be able to use it, but for i..."
97,2026/01/14 12:06:27 AM EST,First Last 84,Yes,23,Junior,4,2,2,Yes,I think that we can use AI sometimes for codin...
98,2026/01/14 9:22:19 AM EST,First Last 85,Yes,21,Junior,4,2,4,Yes,"I don't think we should shy away from it, but ..."
99,2026/01/14 9:24:54 AM EST,First 86,No,21,Junior,3,4,1,Yes,"Just as a coding partner, a place to review th..."

In [8]:
df.shape

(100, 10)

In [9]:
df.describe()

,How old are you?,"How familiar are you with ""data science""?","How familiar are you with ""social science""",How nervous are you for this class?
count,100.000000,100.000000,100.000000,100.000000
mean,21.010000,3.210000,2.910000,3.190000
std,3.767203,0.868006,1.015983,1.228409
min,18.000000,1.000000,1.000000,1.000000
25%,19.000000,3.000000,2.000000,2.000000
50%,20.000000,3.000000,3.000000,3.000000
75%,21.000000,4.000000,3.250000,4.000000
max,35.000000,5.000000,5.000000,5.000000

In [10]:
df.columns

Index(['Timestamp', 'What is your name?', 'Did you grow up in North Carolina?',
       'How old are you?', 'What level of a student are you?',
       'How familiar are you with "data science"?',
       'How familiar are you with "social science"',
       'How nervous are you for this class?',
       'Are you excited for this class?',
       'How do you think generative AI should be used or treated in this course? Don't be shy, we're looking for honest, insightful ideas,'],
      dtype='object')

TODO: Discuss and write down: types of questions and possible cleaning we will need to do. Use your tools!

### Possible questions to answer:
- average age of students
- general vibes/feelings of the class. where to focus the class?
- with lower level of familiarity -> maybe slower, more hollistic approach
- average time students submitted the form
- general views on AI
- how far along students are in their program of study

### Possible data cleaning:
- if no names or identifiers - what do we do about that
- how do we handle duplicates?
- check data types
- consider quotations in open ended text feautures and how to handle them